using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Newtonsoft.Json;

namespace PlayniteAchievements.Models.Settings
{
    public partial class PersistedSettings
    {
        private AchievementGridOptions AchievementDefault => GridOptions.GetAchievement(GridOptionKeys.Achievement.Default);
        private AchievementGridOptions AchievementSingleGame => GridOptions.GetAchievement(GridOptionKeys.Achievement.SingleGame);
        private AchievementGridOptions AchievementOverviewRecent => GridOptions.GetAchievement(GridOptionKeys.Achievement.OverviewRecent);
        private AchievementGridOptions AchievementOverviewSelectedGame => GridOptions.GetAchievement(GridOptionKeys.Achievement.OverviewSelectedGame);
        private AchievementGridOptions AchievementFriendsOverviewRecent => GridOptions.GetAchievement(GridOptionKeys.Achievement.FriendsOverviewRecent);
        private AchievementGridOptions AchievementViewFriendsAchievements => GridOptions.GetAchievement(GridOptionKeys.Achievement.ViewFriendsAchievements);
        private AchievementGridOptions AchievementStartPageRecent => GridOptions.GetAchievement(GridOptionKeys.Achievement.StartPageRecent);
        private AchievementGridOptions AchievementStartPageFriendRecent => GridOptions.GetAchievement(GridOptionKeys.Achievement.StartPageFriendAchievements);
        private AchievementGridOptions AchievementDesktopTheme => GridOptions.GetAchievement(GridOptionKeys.Achievement.DesktopTheme);
        private GameSummaryGridOptions GameSummariesOverview => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.Overview);
        private GameSummaryGridOptions GameSummariesStartPage => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.StartPage);
        private GameSummaryGridOptions GameSummariesViewAchievements => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.ViewAchievements);
        private GameSummaryGridOptions GameSummariesFriendsOverview => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.FriendsOverview);
        private GameSummaryGridOptions GameSummariesFriendsOverviewSelectedFriend => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.FriendsOverviewSelectedFriend);
        private GameSummaryGridOptions GameSummariesViewFriendsAchievements => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.ViewFriendsAchievements);
        private GameSummaryGridOptions GameSummariesViewFriendsAchievementsSelectedFriend => GridOptions.GetGameSummaries(GridOptionKeys.GameSummaries.ViewFriendsAchievementsSelectedFriend);
        private FriendSummaryGridOptions FriendSummariesFriendsOverview => GridOptions.GetFriendSummaries(GridOptionKeys.FriendSummaries.FriendsOverview);
        private CategorySummaryGridOptions CategorySummariesViewAchievements => GridOptions.GetCategorySummaries(GridOptionKeys.CategorySummaries.ViewAchievements);
        private CategorySummaryGridOptions CategorySummariesOverviewSelectedGame => GridOptions.GetCategorySummaries(GridOptionKeys.CategorySummaries.OverviewSelectedGame);
        private CategorySummaryGridOptions CategorySummariesFriendsOverview => GridOptions.GetCategorySummaries(GridOptionKeys.CategorySummaries.FriendsOverview);
        private CategorySummaryGridOptions CategorySummariesViewFriendsAchievements => GridOptions.GetCategorySummaries(GridOptionKeys.CategorySummaries.ViewFriendsAchievements);
        private CategorySummaryGridOptions CategorySummariesDesktopTheme => GridOptions.GetCategorySummaries(GridOptionKeys.CategorySummaries.DesktopTheme);

        private void SetGridValue<T>(
            T current,
            Action<T> set,
            T value,
            [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(current, value))
            {
                return;
            }

            set(value);
            OnPropertyChanged(propertyName);
        }

        [JsonIgnore] public bool OverviewRecentAchievementsShowRarityGlow { get => AchievementOverviewRecent.ShowRarityGlow; set => SetGridValue(OverviewRecentAchievementsShowRarityGlow, v => AchievementOverviewRecent.ShowRarityGlow = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameShowRarityGlow { get => AchievementOverviewSelectedGame.ShowRarityGlow; set => SetGridValue(OverviewSelectedGameShowRarityGlow, v => AchievementOverviewSelectedGame.ShowRarityGlow = v, value); }
        [JsonIgnore] public bool ModernDataGridShowRarityGlow { get => AchievementDefault.ShowRarityGlow; set => SetGridValue(ModernDataGridShowRarityGlow, v => AchievementDefault.ShowRarityGlow = v, value); }
        [JsonIgnore] public bool OverviewRecentAchievementsColorNamesByRarity { get => AchievementOverviewRecent.ColorNamesByRarity; set => SetGridValue(OverviewRecentAchievementsColorNamesByRarity, v => AchievementOverviewRecent.ColorNamesByRarity = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameColorNamesByRarity { get => AchievementOverviewSelectedGame.ColorNamesByRarity; set => SetGridValue(OverviewSelectedGameColorNamesByRarity, v => AchievementOverviewSelectedGame.ColorNamesByRarity = v, value); }
        [JsonIgnore] public bool ModernDataGridColorNamesByRarity { get => AchievementDefault.ColorNamesByRarity; set => SetGridValue(ModernDataGridColorNamesByRarity, v => AchievementDefault.ColorNamesByRarity = v, value); }
        [JsonIgnore] public bool OverviewRecentAchievementsColorRarityColumnsByRarity { get => AchievementOverviewRecent.ColorRarityColumnsByRarity; set => SetGridValue(OverviewRecentAchievementsColorRarityColumnsByRarity, v => AchievementOverviewRecent.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameColorRarityColumnsByRarity { get => AchievementOverviewSelectedGame.ColorRarityColumnsByRarity; set => SetGridValue(OverviewSelectedGameColorRarityColumnsByRarity, v => AchievementOverviewSelectedGame.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewAchievementsAchievementGridColorRarityColumnsByRarity { get => AchievementSingleGame.ColorRarityColumnsByRarity; set => SetGridValue(ViewAchievementsAchievementGridColorRarityColumnsByRarity, v => AchievementSingleGame.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewFriendsAchievementsColorRarityColumnsByRarity { get => AchievementViewFriendsAchievements.ColorRarityColumnsByRarity; set => SetGridValue(ViewFriendsAchievementsColorRarityColumnsByRarity, v => AchievementViewFriendsAchievements.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ModernDataGridColorRarityColumnsByRarity { get => AchievementDefault.ColorRarityColumnsByRarity; set => SetGridValue(ModernDataGridColorRarityColumnsByRarity, v => AchievementDefault.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool OverviewGameSummariesColorRarityColumnsByRarity { get => GameSummariesOverview.ColorRarityColumnsByRarity; set => SetGridValue(OverviewGameSummariesColorRarityColumnsByRarity, v => GameSummariesOverview.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool StartPageGameSummariesColorRarityColumnsByRarity { get => GameSummariesStartPage.ColorRarityColumnsByRarity; set => SetGridValue(StartPageGameSummariesColorRarityColumnsByRarity, v => GameSummariesStartPage.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewAchievementsGameSummariesColorRarityColumnsByRarity { get => GameSummariesViewAchievements.ColorRarityColumnsByRarity; set => SetGridValue(ViewAchievementsGameSummariesColorRarityColumnsByRarity, v => GameSummariesViewAchievements.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesColorRarityColumnsByRarity { get => GameSummariesFriendsOverview.ColorRarityColumnsByRarity; set => SetGridValue(FriendsOverviewGameSummariesColorRarityColumnsByRarity, v => GameSummariesFriendsOverview.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool FriendsOverviewSelectedFriendGameSummariesColorRarityColumnsByRarity { get => GameSummariesFriendsOverviewSelectedFriend.ColorRarityColumnsByRarity; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColorRarityColumnsByRarity, v => GameSummariesFriendsOverviewSelectedFriend.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewFriendsAchievementsGameSummariesColorRarityColumnsByRarity { get => GameSummariesViewFriendsAchievements.ColorRarityColumnsByRarity; set => SetGridValue(ViewFriendsAchievementsGameSummariesColorRarityColumnsByRarity, v => GameSummariesViewFriendsAchievements.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewFriendsAchievementsSelectedFriendGameSummariesColorRarityColumnsByRarity { get => GameSummariesViewFriendsAchievementsSelectedFriend.ColorRarityColumnsByRarity; set => SetGridValue(ViewFriendsAchievementsSelectedFriendGameSummariesColorRarityColumnsByRarity, v => GameSummariesViewFriendsAchievementsSelectedFriend.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewAchievementsCategorySummariesColorRarityColumnsByRarity { get => CategorySummariesViewAchievements.ColorRarityColumnsByRarity; set => SetGridValue(ViewAchievementsCategorySummariesColorRarityColumnsByRarity, v => CategorySummariesViewAchievements.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameCategorySummariesColorRarityColumnsByRarity { get => CategorySummariesOverviewSelectedGame.ColorRarityColumnsByRarity; set => SetGridValue(OverviewSelectedGameCategorySummariesColorRarityColumnsByRarity, v => CategorySummariesOverviewSelectedGame.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool FriendsOverviewCategorySummariesColorRarityColumnsByRarity { get => CategorySummariesFriendsOverview.ColorRarityColumnsByRarity; set => SetGridValue(FriendsOverviewCategorySummariesColorRarityColumnsByRarity, v => CategorySummariesFriendsOverview.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool ViewFriendsAchievementsCategorySummariesColorRarityColumnsByRarity { get => CategorySummariesViewFriendsAchievements.ColorRarityColumnsByRarity; set => SetGridValue(ViewFriendsAchievementsCategorySummariesColorRarityColumnsByRarity, v => CategorySummariesViewFriendsAchievements.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool DesktopThemeCategorySummariesColorRarityColumnsByRarity { get => CategorySummariesDesktopTheme.ColorRarityColumnsByRarity; set => SetGridValue(DesktopThemeCategorySummariesColorRarityColumnsByRarity, v => CategorySummariesDesktopTheme.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool OverviewGameSummariesUseCoverImages { get => GameSummariesOverview.UseCoverImages; set => SetGridValue(OverviewGameSummariesUseCoverImages, v => GameSummariesOverview.UseCoverImages = v, value); }
        [JsonIgnore] public bool OverviewRecentAchievementsUseCoverImages { get => AchievementOverviewRecent.UseCoverImages; set => SetGridValue(OverviewRecentAchievementsUseCoverImages, v => AchievementOverviewRecent.UseCoverImages = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesUseCoverImages { get => GameSummariesFriendsOverview.UseCoverImages; set => SetGridValue(FriendsOverviewGameSummariesUseCoverImages, v => GameSummariesFriendsOverview.UseCoverImages = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesShowMetadataPlatform { get => GameSummariesFriendsOverview.ShowMetadataPlatform; set => SetGridValue(FriendsOverviewGameSummariesShowMetadataPlatform, v => GameSummariesFriendsOverview.ShowMetadataPlatform = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesShowMetadataPlaytime { get => GameSummariesFriendsOverview.ShowMetadataPlaytime; set => SetGridValue(FriendsOverviewGameSummariesShowMetadataPlaytime, v => GameSummariesFriendsOverview.ShowMetadataPlaytime = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesShowMetadataRegion { get => GameSummariesFriendsOverview.ShowMetadataRegion; set => SetGridValue(FriendsOverviewGameSummariesShowMetadataRegion, v => GameSummariesFriendsOverview.ShowMetadataRegion = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesShowCompletionGlow { get => GameSummariesFriendsOverview.ShowCompletionGlow; set => SetGridValue(FriendsOverviewGameSummariesShowCompletionGlow, v => GameSummariesFriendsOverview.ShowCompletionGlow = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsUseCoverImages { get => AchievementFriendsOverviewRecent.UseCoverImages; set => SetGridValue(FriendsOverviewAchievementsUseCoverImages, v => AchievementFriendsOverviewRecent.UseCoverImages = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsShowRarityGlow { get => AchievementFriendsOverviewRecent.ShowRarityGlow; set => SetGridValue(FriendsOverviewAchievementsShowRarityGlow, v => AchievementFriendsOverviewRecent.ShowRarityGlow = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsColorNamesByRarity { get => AchievementFriendsOverviewRecent.ColorNamesByRarity; set => SetGridValue(FriendsOverviewAchievementsColorNamesByRarity, v => AchievementFriendsOverviewRecent.ColorNamesByRarity = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsColorRarityColumnsByRarity { get => AchievementFriendsOverviewRecent.ColorRarityColumnsByRarity; set => SetGridValue(FriendsOverviewAchievementsColorRarityColumnsByRarity, v => AchievementFriendsOverviewRecent.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool StartPageFriendsRecentAchievementsUseCoverImages { get => AchievementStartPageFriendRecent.UseCoverImages; set => SetGridValue(StartPageFriendsRecentAchievementsUseCoverImages, v => AchievementStartPageFriendRecent.UseCoverImages = v, value); }
        [JsonIgnore] public bool StartPageFriendsRecentAchievementsShowRarityGlow { get => AchievementStartPageFriendRecent.ShowRarityGlow; set => SetGridValue(StartPageFriendsRecentAchievementsShowRarityGlow, v => AchievementStartPageFriendRecent.ShowRarityGlow = v, value); }
        [JsonIgnore] public bool StartPageFriendsRecentAchievementsColorNamesByRarity { get => AchievementStartPageFriendRecent.ColorNamesByRarity; set => SetGridValue(StartPageFriendsRecentAchievementsColorNamesByRarity, v => AchievementStartPageFriendRecent.ColorNamesByRarity = v, value); }
        [JsonIgnore] public bool StartPageFriendsRecentAchievementsColorRarityColumnsByRarity { get => AchievementStartPageFriendRecent.ColorRarityColumnsByRarity; set => SetGridValue(StartPageFriendsRecentAchievementsColorRarityColumnsByRarity, v => AchievementStartPageFriendRecent.ColorRarityColumnsByRarity = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameAchievementsStartInCategoryMode { get => AchievementOverviewSelectedGame.StartInCategoryMode; set => SetGridValue(OverviewSelectedGameAchievementsStartInCategoryMode, v => AchievementOverviewSelectedGame.StartInCategoryMode = v, value); }
        [JsonIgnore] public bool ViewAchievementsAchievementGridStartInCategoryMode { get => AchievementSingleGame.StartInCategoryMode; set => SetGridValue(ViewAchievementsAchievementGridStartInCategoryMode, v => AchievementSingleGame.StartInCategoryMode = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsStartInCategoryMode { get => AchievementFriendsOverviewRecent.StartInCategoryMode; set => SetGridValue(FriendsOverviewAchievementsStartInCategoryMode, v => AchievementFriendsOverviewRecent.StartInCategoryMode = v, value); }
        [JsonIgnore] public bool DesktopThemeAchievementGridStartInCategoryMode { get => AchievementDesktopTheme.StartInCategoryMode; set => SetGridValue(DesktopThemeAchievementGridStartInCategoryMode, v => AchievementDesktopTheme.StartInCategoryMode = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameAchievementsHideCategorySummaryRow { get => AchievementOverviewSelectedGame.HideCategorySummaryRow; set => SetGridValue(OverviewSelectedGameAchievementsHideCategorySummaryRow, v => AchievementOverviewSelectedGame.HideCategorySummaryRow = v, value); }
        [JsonIgnore] public bool ViewAchievementsAchievementGridHideCategorySummaryRow { get => AchievementSingleGame.HideCategorySummaryRow; set => SetGridValue(ViewAchievementsAchievementGridHideCategorySummaryRow, v => AchievementSingleGame.HideCategorySummaryRow = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsHideCategorySummaryRow { get => AchievementFriendsOverviewRecent.HideCategorySummaryRow; set => SetGridValue(FriendsOverviewAchievementsHideCategorySummaryRow, v => AchievementFriendsOverviewRecent.HideCategorySummaryRow = v, value); }
        [JsonIgnore] public bool DesktopThemeAchievementGridHideCategorySummaryRow { get => AchievementDesktopTheme.HideCategorySummaryRow; set => SetGridValue(DesktopThemeAchievementGridHideCategorySummaryRow, v => AchievementDesktopTheme.HideCategorySummaryRow = v, value); }
        [JsonIgnore] public bool ShowCompletionGlow { get => GameSummariesOverview.ShowCompletionGlow; set => SetGridValue(ShowCompletionGlow, v => GameSummariesOverview.ShowCompletionGlow = v, value); }
        [JsonIgnore] public bool ShowOverviewGameMetadataPlatform { get => GameSummariesOverview.ShowMetadataPlatform; set => SetGridValue(ShowOverviewGameMetadataPlatform, v => GameSummariesOverview.ShowMetadataPlatform = v, value); }
        [JsonIgnore] public bool ShowOverviewGameMetadataPlaytime { get => GameSummariesOverview.ShowMetadataPlaytime; set => SetGridValue(ShowOverviewGameMetadataPlaytime, v => GameSummariesOverview.ShowMetadataPlaytime = v, value); }
        [JsonIgnore] public bool ShowOverviewGameMetadataRegion { get => GameSummariesOverview.ShowMetadataRegion; set => SetGridValue(ShowOverviewGameMetadataRegion, v => GameSummariesOverview.ShowMetadataRegion = v, value); }
        [JsonIgnore] public bool ShowOverviewGameSummariesGridColumnHeaders { get => GameSummariesOverview.ShowColumnHeaders; set => SetGridValue(ShowOverviewGameSummariesGridColumnHeaders, v => GameSummariesOverview.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewFriendSummariesGridColumnHeaders { get => FriendSummariesFriendsOverview.ShowColumnHeaders; set => SetGridValue(ShowFriendsOverviewFriendSummariesGridColumnHeaders, v => FriendSummariesFriendsOverview.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewGameSummariesGridColumnHeaders { get => GameSummariesFriendsOverview.ShowColumnHeaders; set => SetGridValue(ShowFriendsOverviewGameSummariesGridColumnHeaders, v => GameSummariesFriendsOverview.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewAchievementsGridColumnHeaders { get => AchievementFriendsOverviewRecent.ShowColumnHeaders; set => SetGridValue(ShowFriendsOverviewAchievementsGridColumnHeaders, v => AchievementFriendsOverviewRecent.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowOverviewGameSummariesGridControlBar { get => GameSummariesOverview.ShowControlBar; set => SetGridValue(ShowOverviewGameSummariesGridControlBar, v => GameSummariesOverview.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowOverviewRecentAchievementsGridControlBar { get => AchievementOverviewRecent.ShowControlBar; set => SetGridValue(ShowOverviewRecentAchievementsGridControlBar, v => AchievementOverviewRecent.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowOverviewSelectedGameGridControlBar { get => AchievementOverviewSelectedGame.ShowControlBar; set => SetGridValue(ShowOverviewSelectedGameGridControlBar, v => AchievementOverviewSelectedGame.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowViewAchievementsAchievementGridControlBar { get => AchievementSingleGame.ShowControlBar; set => SetGridValue(ShowViewAchievementsAchievementGridControlBar, v => AchievementSingleGame.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowDesktopThemeAchievementGridControlBar { get => AchievementDesktopTheme.ShowControlBar; set => SetGridValue(ShowDesktopThemeAchievementGridControlBar, v => AchievementDesktopTheme.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewFriendSummariesGridControlBar { get => FriendSummariesFriendsOverview.ShowControlBar; set => SetGridValue(ShowFriendsOverviewFriendSummariesGridControlBar, v => FriendSummariesFriendsOverview.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewGameSummariesGridControlBar { get => GameSummariesFriendsOverview.ShowControlBar; set => SetGridValue(ShowFriendsOverviewGameSummariesGridControlBar, v => GameSummariesFriendsOverview.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewAchievementsGridControlBar { get => AchievementFriendsOverviewRecent.ShowControlBar; set => SetGridValue(ShowFriendsOverviewAchievementsGridControlBar, v => AchievementFriendsOverviewRecent.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowStartPageFriendsRecentAchievementsGridControlBar { get => AchievementStartPageFriendRecent.ShowControlBar; set => SetGridValue(ShowStartPageFriendsRecentAchievementsGridControlBar, v => AchievementStartPageFriendRecent.ShowControlBar = v, value); }
        [JsonIgnore] public bool ShowOverviewRecentAchievementsGridColumnHeaders { get => AchievementOverviewRecent.ShowColumnHeaders; set => SetGridValue(ShowOverviewRecentAchievementsGridColumnHeaders, v => AchievementOverviewRecent.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowOverviewSelectedGameGridColumnHeaders { get => AchievementOverviewSelectedGame.ShowColumnHeaders; set => SetGridValue(ShowOverviewSelectedGameGridColumnHeaders, v => AchievementOverviewSelectedGame.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowDesktopThemeAchievementGridColumnHeaders { get => AchievementDesktopTheme.ShowColumnHeaders; set => SetGridValue(ShowDesktopThemeAchievementGridColumnHeaders, v => AchievementDesktopTheme.ShowColumnHeaders = v, value); }
        [JsonIgnore] public bool ShowStartPageFriendsRecentAchievementsGridColumnHeaders { get => AchievementStartPageFriendRecent.ShowColumnHeaders; set => SetGridValue(ShowStartPageFriendsRecentAchievementsGridColumnHeaders, v => AchievementStartPageFriendRecent.ShowColumnHeaders = v, value); }
        [JsonIgnore] public DateDisplayMode OverviewGameSummariesLastPlayedDateMode { get => GameSummariesOverview.LastPlayedDateMode; set => SetGridValue(OverviewGameSummariesLastPlayedDateMode, v => GameSummariesOverview.LastPlayedDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode ViewAchievementsGameSummariesLastPlayedDateMode { get => GameSummariesViewAchievements.LastPlayedDateMode; set => SetGridValue(ViewAchievementsGameSummariesLastPlayedDateMode, v => GameSummariesViewAchievements.LastPlayedDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode StartPageGameSummariesLastPlayedDateMode { get => GameSummariesStartPage.LastPlayedDateMode; set => SetGridValue(StartPageGameSummariesLastPlayedDateMode, v => GameSummariesStartPage.LastPlayedDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode FriendsOverviewFriendSummariesLastUnlockDateMode { get => FriendSummariesFriendsOverview.LastUnlockDateMode; set => SetGridValue(FriendsOverviewFriendSummariesLastUnlockDateMode, v => FriendSummariesFriendsOverview.LastUnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode FriendsOverviewGameSummariesLastPlayedDateMode { get => GameSummariesFriendsOverview.LastPlayedDateMode; set => SetGridValue(FriendsOverviewGameSummariesLastPlayedDateMode, v => GameSummariesFriendsOverview.LastPlayedDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode OverviewRecentAchievementsUnlockDateMode { get => AchievementOverviewRecent.UnlockDateMode; set => SetGridValue(OverviewRecentAchievementsUnlockDateMode, v => AchievementOverviewRecent.UnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode FriendsOverviewAchievementsUnlockDateMode { get => AchievementFriendsOverviewRecent.UnlockDateMode; set => SetGridValue(FriendsOverviewAchievementsUnlockDateMode, v => AchievementFriendsOverviewRecent.UnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode OverviewSelectedGameAchievementsUnlockDateMode { get => AchievementOverviewSelectedGame.UnlockDateMode; set => SetGridValue(OverviewSelectedGameAchievementsUnlockDateMode, v => AchievementOverviewSelectedGame.UnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode ViewAchievementsAchievementsUnlockDateMode { get => AchievementSingleGame.UnlockDateMode; set => SetGridValue(ViewAchievementsAchievementsUnlockDateMode, v => AchievementSingleGame.UnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode StartPageAchievementsUnlockDateMode { get => AchievementStartPageRecent.UnlockDateMode; set => SetGridValue(StartPageAchievementsUnlockDateMode, v => AchievementStartPageRecent.UnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode StartPageFriendsRecentAchievementsUnlockDateMode { get => AchievementStartPageFriendRecent.UnlockDateMode; set => SetGridValue(StartPageFriendsRecentAchievementsUnlockDateMode, v => AchievementStartPageFriendRecent.UnlockDateMode = v, value); }
        [JsonIgnore] public DateDisplayMode DesktopThemeAchievementsUnlockDateMode { get => AchievementDesktopTheme.UnlockDateMode; set => SetGridValue(DesktopThemeAchievementsUnlockDateMode, v => AchievementDesktopTheme.UnlockDateMode = v, value); }
        [JsonIgnore] public GameSummariesSortMode OverviewGameSummariesGridSortMode { get => GameSummariesOverview.SortMode; set => SetGridValue(OverviewGameSummariesGridSortMode, v => GameSummariesOverview.SortMode = v, value); }
        [JsonIgnore] public bool OverviewGameSummariesGridSortDescending { get => GameSummariesOverview.SortDescending; set => SetGridValue(OverviewGameSummariesGridSortDescending, v => GameSummariesOverview.SortDescending = v, value); }
        [JsonIgnore] public CompactListSortMode OverviewSelectedGameGridSortMode { get => AchievementOverviewSelectedGame.SortMode; set => SetGridValue(OverviewSelectedGameGridSortMode, v => AchievementOverviewSelectedGame.SortMode = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameGridSortDescending { get => AchievementOverviewSelectedGame.SortDescending; set => SetGridValue(OverviewSelectedGameGridSortDescending, v => AchievementOverviewSelectedGame.SortDescending = v, value); }
        [JsonIgnore] public CompactListSortMode SingleGameGridSortMode { get => AchievementSingleGame.SortMode; set => SetGridValue(SingleGameGridSortMode, v => AchievementSingleGame.SortMode = v, value); }
        [JsonIgnore] public bool SingleGameGridSortDescending { get => AchievementSingleGame.SortDescending; set => SetGridValue(SingleGameGridSortDescending, v => AchievementSingleGame.SortDescending = v, value); }
        [JsonIgnore] public CompactListSortMode AchievementDataGridSortMode { get => AchievementDefault.SortMode; set => SetGridValue(AchievementDataGridSortMode, v => AchievementDefault.SortMode = v, value); }
        [JsonIgnore] public bool AchievementDataGridSortDescending { get => AchievementDefault.SortDescending; set => SetGridValue(AchievementDataGridSortDescending, v => AchievementDefault.SortDescending = v, value); }
        [JsonIgnore] public FriendSummariesSortMode FriendsOverviewFriendSummariesGridSortMode { get => FriendSummariesFriendsOverview.SortMode; set => SetGridValue(FriendsOverviewFriendSummariesGridSortMode, v => FriendSummariesFriendsOverview.SortMode = v, value); }
        [JsonIgnore] public bool FriendsOverviewFriendSummariesGridSortDescending { get => FriendSummariesFriendsOverview.SortDescending; set => SetGridValue(FriendsOverviewFriendSummariesGridSortDescending, v => FriendSummariesFriendsOverview.SortDescending = v, value); }
        [JsonIgnore] public GameSummariesSortMode FriendsOverviewGameSummariesGridSortMode { get => GameSummariesFriendsOverview.SortMode; set => SetGridValue(FriendsOverviewGameSummariesGridSortMode, v => GameSummariesFriendsOverview.SortMode = v, value); }
        [JsonIgnore] public bool FriendsOverviewGameSummariesGridSortDescending { get => GameSummariesFriendsOverview.SortDescending; set => SetGridValue(FriendsOverviewGameSummariesGridSortDescending, v => GameSummariesFriendsOverview.SortDescending = v, value); }
        [JsonIgnore] public CompactListSortMode FriendsOverviewAchievementsGridSortMode { get => AchievementFriendsOverviewRecent.SortMode; set => SetGridValue(FriendsOverviewAchievementsGridSortMode, v => AchievementFriendsOverviewRecent.SortMode = v, value); }
        [JsonIgnore] public bool FriendsOverviewAchievementsGridSortDescending { get => AchievementFriendsOverviewRecent.SortDescending; set => SetGridValue(FriendsOverviewAchievementsGridSortDescending, v => AchievementFriendsOverviewRecent.SortDescending = v, value); }
        [JsonIgnore] public double? AchievementDataGridMaxHeight { get => AchievementDefault.MaxHeight; set => SetGridValue(AchievementDataGridMaxHeight, v => AchievementDefault.MaxHeight = v, value); }
        [JsonIgnore] public double? SingleGameGridRowHeight { get => AchievementSingleGame.RowHeight; set => SetGridValue(SingleGameGridRowHeight, v => AchievementSingleGame.RowHeight = v, value); }
        [JsonIgnore] public double? OverviewGameSummariesGridRowHeight { get => GameSummariesOverview.RowHeight; set => SetGridValue(OverviewGameSummariesGridRowHeight, v => GameSummariesOverview.RowHeight = v, value); }
        [JsonIgnore] public double? OverviewRecentAchievementsGridRowHeight { get => AchievementOverviewRecent.RowHeight; set => SetGridValue(OverviewRecentAchievementsGridRowHeight, v => AchievementOverviewRecent.RowHeight = v, value); }
        [JsonIgnore] public double? OverviewSelectedGameGridRowHeight { get => AchievementOverviewSelectedGame.RowHeight; set => SetGridValue(OverviewSelectedGameGridRowHeight, v => AchievementOverviewSelectedGame.RowHeight = v, value); }
        [JsonIgnore] public double? StartPageGameSummariesGridRowHeight { get => GameSummariesStartPage.RowHeight; set => SetGridValue(StartPageGameSummariesGridRowHeight, v => GameSummariesStartPage.RowHeight = v, value); }
        [JsonIgnore] public double? StartPageRecentAchievementsGridRowHeight { get => AchievementStartPageRecent.RowHeight; set => SetGridValue(StartPageRecentAchievementsGridRowHeight, v => AchievementStartPageRecent.RowHeight = v, value); }
        [JsonIgnore] public double? StartPageFriendsRecentAchievementsGridRowHeight { get => AchievementStartPageFriendRecent.RowHeight; set => SetGridValue(StartPageFriendsRecentAchievementsGridRowHeight, v => AchievementStartPageFriendRecent.RowHeight = v, value); }
        [JsonIgnore] public double? FriendsOverviewFriendSummariesGridRowHeight { get => FriendSummariesFriendsOverview.RowHeight; set => SetGridValue(FriendsOverviewFriendSummariesGridRowHeight, v => FriendSummariesFriendsOverview.RowHeight = v, value); }
        [JsonIgnore] public double? FriendsOverviewGameSummariesGridRowHeight { get => GameSummariesFriendsOverview.RowHeight; set => SetGridValue(FriendsOverviewGameSummariesGridRowHeight, v => GameSummariesFriendsOverview.RowHeight = v, value); }
        [JsonIgnore] public double? FriendsOverviewAchievementsGridRowHeight { get => AchievementFriendsOverviewRecent.RowHeight; set => SetGridValue(FriendsOverviewAchievementsGridRowHeight, v => AchievementFriendsOverviewRecent.RowHeight = v, value); }
        [JsonIgnore] public double? DesktopThemeAchievementGridRowHeight { get => AchievementDesktopTheme.RowHeight; set => SetGridValue(DesktopThemeAchievementGridRowHeight, v => AchievementDesktopTheme.RowHeight = v, value); }
        [JsonIgnore] public int? SingleGameGridMaxRows { get => AchievementSingleGame.MaxRows; set => SetGridValue(SingleGameGridMaxRows, v => AchievementSingleGame.MaxRows = v, value); }
        [JsonIgnore] public int? OverviewGameSummariesGridMaxRows { get => GameSummariesOverview.MaxRows; set => SetGridValue(OverviewGameSummariesGridMaxRows, v => GameSummariesOverview.MaxRows = v, value); }
        [JsonIgnore] public int? OverviewRecentAchievementsGridMaxRows { get => AchievementOverviewRecent.MaxRows; set => SetGridValue(OverviewRecentAchievementsGridMaxRows, v => AchievementOverviewRecent.MaxRows = v, value); }
        [JsonIgnore] public int? OverviewSelectedGameGridMaxRows { get => AchievementOverviewSelectedGame.MaxRows; set => SetGridValue(OverviewSelectedGameGridMaxRows, v => AchievementOverviewSelectedGame.MaxRows = v, value); }
        [JsonIgnore] public int? StartPageGameSummariesGridMaxRows { get => GameSummariesStartPage.MaxRows; set => SetGridValue(StartPageGameSummariesGridMaxRows, v => GameSummariesStartPage.MaxRows = v, value); }
        [JsonIgnore] public int? StartPageRecentAchievementsGridMaxRows { get => AchievementStartPageRecent.MaxRows; set => SetGridValue(StartPageRecentAchievementsGridMaxRows, v => AchievementStartPageRecent.MaxRows = v, value); }
        [JsonIgnore] public int? StartPageFriendsRecentAchievementsGridMaxRows { get => AchievementStartPageFriendRecent.MaxRows; set => SetGridValue(StartPageFriendsRecentAchievementsGridMaxRows, v => AchievementStartPageFriendRecent.MaxRows = v, value); }
        [JsonIgnore] public int? FriendsOverviewFriendSummariesGridMaxRows { get => FriendSummariesFriendsOverview.MaxRows; set => SetGridValue(FriendsOverviewFriendSummariesGridMaxRows, v => FriendSummariesFriendsOverview.MaxRows = v, value); }
        [JsonIgnore] public int? FriendsOverviewGameSummariesGridMaxRows { get => GameSummariesFriendsOverview.MaxRows; set => SetGridValue(FriendsOverviewGameSummariesGridMaxRows, v => GameSummariesFriendsOverview.MaxRows = v, value); }
        [JsonIgnore] public int? FriendsOverviewAchievementsGridMaxRows { get => AchievementFriendsOverviewRecent.MaxRows; set => SetGridValue(FriendsOverviewAchievementsGridMaxRows, v => AchievementFriendsOverviewRecent.MaxRows = v, value); }
        [JsonIgnore] public int? DesktopThemeAchievementGridMaxRows { get => AchievementDesktopTheme.MaxRows; set => SetGridValue(DesktopThemeAchievementGridMaxRows, v => AchievementDesktopTheme.MaxRows = v, value); }
        [JsonIgnore] public bool ViewAchievementsGameSummariesUseCoverImages { get => GameSummariesViewAchievements.UseCoverImages; set => SetGridValue(ViewAchievementsGameSummariesUseCoverImages, v => GameSummariesViewAchievements.UseCoverImages = v, value); }
        [JsonIgnore] public bool ViewAchievementsGameSummariesShowMetadataPlatform { get => GameSummariesViewAchievements.ShowMetadataPlatform; set => SetGridValue(ViewAchievementsGameSummariesShowMetadataPlatform, v => GameSummariesViewAchievements.ShowMetadataPlatform = v, value); }
        [JsonIgnore] public bool ViewAchievementsGameSummariesShowMetadataPlaytime { get => GameSummariesViewAchievements.ShowMetadataPlaytime; set => SetGridValue(ViewAchievementsGameSummariesShowMetadataPlaytime, v => GameSummariesViewAchievements.ShowMetadataPlaytime = v, value); }
        [JsonIgnore] public bool ViewAchievementsGameSummariesShowMetadataRegion { get => GameSummariesViewAchievements.ShowMetadataRegion; set => SetGridValue(ViewAchievementsGameSummariesShowMetadataRegion, v => GameSummariesViewAchievements.ShowMetadataRegion = v, value); }
        [JsonIgnore] public bool ViewAchievementsGameSummariesShowCompletionGlow { get => GameSummariesViewAchievements.ShowCompletionGlow; set => SetGridValue(ViewAchievementsGameSummariesShowCompletionGlow, v => GameSummariesViewAchievements.ShowCompletionGlow = v, value); }
        [JsonIgnore] public bool ShowViewAchievementsGameSummariesGridColumnHeaders { get => GameSummariesViewAchievements.ShowColumnHeaders; set => SetGridValue(ShowViewAchievementsGameSummariesGridColumnHeaders, v => GameSummariesViewAchievements.ShowColumnHeaders = v, value); }
        [JsonIgnore] public double? ViewAchievementsGameSummariesGridRowHeight { get => GameSummariesViewAchievements.RowHeight; set => SetGridValue(ViewAchievementsGameSummariesGridRowHeight, v => GameSummariesViewAchievements.RowHeight = v, value); }

        [JsonIgnore]
        public StartPageGameSummariesGridSettings StartPageGameSummariesGrid
        {
            get
            {
                RebindStartPageGridSettings();
                return _startPageGameSummariesGrid ?? (_startPageGameSummariesGrid = AttachStartPageSettings(new StartPageGameSummariesGridSettings(GameSummariesStartPage)));
            }
            set { (value ?? new StartPageGameSummariesGridSettings()).CopyTo(GameSummariesStartPage); OnPropertyChanged(); }
        }

        [JsonIgnore]
        public StartPageRecentUnlocksGridSettings StartPageRecentUnlocksGrid
        {
            get
            {
                RebindStartPageGridSettings();
                return _startPageRecentUnlocksGrid ?? (_startPageRecentUnlocksGrid = AttachStartPageSettings(new StartPageRecentUnlocksGridSettings(AchievementStartPageRecent)));
            }
            set { (value ?? new StartPageRecentUnlocksGridSettings()).CopyTo(AchievementStartPageRecent); OnPropertyChanged(); }
        }

        [JsonIgnore]
        public StartPageFriendsRecentUnlocksGridSettings StartPageFriendsRecentUnlocksGrid
        {
            get
            {
                RebindStartPageGridSettings();
                return _startPageFriendsRecentUnlocksGrid ?? (_startPageFriendsRecentUnlocksGrid = AttachStartPageSettings(new StartPageFriendsRecentUnlocksGridSettings(AchievementStartPageFriendRecent)));
            }
            set { (value ?? new StartPageFriendsRecentUnlocksGridSettings()).CopyTo(AchievementStartPageFriendRecent); OnPropertyChanged(); }
        }

        [JsonIgnore] public Dictionary<string, bool> DataGridColumnVisibility { get => AchievementDefault.Columns.Visibility; set => SetGridValue(DataGridColumnVisibility, v => AchievementDefault.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> DataGridColumnWidths { get => AchievementDefault.Columns.Widths; set => SetGridValue(DataGridColumnWidths, v => AchievementDefault.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> DataGridColumnOrder { get => AchievementDefault.Columns.Order; set => SetGridValue(DataGridColumnOrder, v => AchievementDefault.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, bool> OverviewRecentAchievementColumnVisibility { get => AchievementOverviewRecent.Columns.Visibility; set => SetGridValue(OverviewRecentAchievementColumnVisibility, v => AchievementOverviewRecent.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> OverviewRecentAchievementColumnWidths { get => AchievementOverviewRecent.Columns.Widths; set => SetGridValue(OverviewRecentAchievementColumnWidths, v => AchievementOverviewRecent.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> OverviewRecentAchievementColumnOrder { get => AchievementOverviewRecent.Columns.Order; set => SetGridValue(OverviewRecentAchievementColumnOrder, v => AchievementOverviewRecent.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewRecentAchievementColumnAlignments { get => AchievementOverviewRecent.Columns.CellAlignments; set => SetGridValue(OverviewRecentAchievementColumnAlignments, v => AchievementOverviewRecent.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> OverviewRecentAchievementColumnVerticalAlignments { get => AchievementOverviewRecent.Columns.CellVerticalAlignments; set => SetGridValue(OverviewRecentAchievementColumnVerticalAlignments, v => AchievementOverviewRecent.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewRecentAchievementColumnHeaderAlignments { get => AchievementOverviewRecent.Columns.HeaderAlignments; set => SetGridValue(OverviewRecentAchievementColumnHeaderAlignments, v => AchievementOverviewRecent.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> FriendsOverviewAchievementColumnVisibility { get => AchievementFriendsOverviewRecent.Columns.Visibility; set => SetGridValue(FriendsOverviewAchievementColumnVisibility, v => AchievementFriendsOverviewRecent.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> FriendsOverviewAchievementColumnWidths { get => AchievementFriendsOverviewRecent.Columns.Widths; set => SetGridValue(FriendsOverviewAchievementColumnWidths, v => AchievementFriendsOverviewRecent.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> FriendsOverviewAchievementColumnOrder { get => AchievementFriendsOverviewRecent.Columns.Order; set => SetGridValue(FriendsOverviewAchievementColumnOrder, v => AchievementFriendsOverviewRecent.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewAchievementColumnAlignments { get => AchievementFriendsOverviewRecent.Columns.CellAlignments; set => SetGridValue(FriendsOverviewAchievementColumnAlignments, v => AchievementFriendsOverviewRecent.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> FriendsOverviewAchievementColumnVerticalAlignments { get => AchievementFriendsOverviewRecent.Columns.CellVerticalAlignments; set => SetGridValue(FriendsOverviewAchievementColumnVerticalAlignments, v => AchievementFriendsOverviewRecent.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewAchievementColumnHeaderAlignments { get => AchievementFriendsOverviewRecent.Columns.HeaderAlignments; set => SetGridValue(FriendsOverviewAchievementColumnHeaderAlignments, v => AchievementFriendsOverviewRecent.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> FriendsOverviewFriendSummariesColumnVisibility { get => FriendSummariesFriendsOverview.Columns.Visibility; set => SetGridValue(FriendsOverviewFriendSummariesColumnVisibility, v => FriendSummariesFriendsOverview.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> FriendsOverviewFriendSummariesColumnWidths { get => FriendSummariesFriendsOverview.Columns.Widths; set => SetGridValue(FriendsOverviewFriendSummariesColumnWidths, v => FriendSummariesFriendsOverview.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> FriendsOverviewFriendSummariesColumnOrder { get => FriendSummariesFriendsOverview.Columns.Order; set => SetGridValue(FriendsOverviewFriendSummariesColumnOrder, v => FriendSummariesFriendsOverview.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewFriendSummariesColumnAlignments { get => FriendSummariesFriendsOverview.Columns.CellAlignments; set => SetGridValue(FriendsOverviewFriendSummariesColumnAlignments, v => FriendSummariesFriendsOverview.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> FriendsOverviewFriendSummariesColumnVerticalAlignments { get => FriendSummariesFriendsOverview.Columns.CellVerticalAlignments; set => SetGridValue(FriendsOverviewFriendSummariesColumnVerticalAlignments, v => FriendSummariesFriendsOverview.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewFriendSummariesColumnHeaderAlignments { get => FriendSummariesFriendsOverview.Columns.HeaderAlignments; set => SetGridValue(FriendsOverviewFriendSummariesColumnHeaderAlignments, v => FriendSummariesFriendsOverview.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> FriendsOverviewGameSummariesColumnVisibility { get => GameSummariesFriendsOverview.Columns.Visibility; set => SetGridValue(FriendsOverviewGameSummariesColumnVisibility, v => GameSummariesFriendsOverview.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> FriendsOverviewGameSummariesColumnWidths { get => GameSummariesFriendsOverview.Columns.Widths; set => SetGridValue(FriendsOverviewGameSummariesColumnWidths, v => GameSummariesFriendsOverview.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> FriendsOverviewGameSummariesColumnOrder { get => GameSummariesFriendsOverview.Columns.Order; set => SetGridValue(FriendsOverviewGameSummariesColumnOrder, v => GameSummariesFriendsOverview.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewGameSummariesColumnAlignments { get => GameSummariesFriendsOverview.Columns.CellAlignments; set => SetGridValue(FriendsOverviewGameSummariesColumnAlignments, v => GameSummariesFriendsOverview.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> FriendsOverviewGameSummariesColumnVerticalAlignments { get => GameSummariesFriendsOverview.Columns.CellVerticalAlignments; set => SetGridValue(FriendsOverviewGameSummariesColumnVerticalAlignments, v => GameSummariesFriendsOverview.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewGameSummariesColumnHeaderAlignments { get => GameSummariesFriendsOverview.Columns.HeaderAlignments; set => SetGridValue(FriendsOverviewGameSummariesColumnHeaderAlignments, v => GameSummariesFriendsOverview.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> FriendsOverviewSelectedFriendGameSummariesColumnVisibility { get => GameSummariesFriendsOverviewSelectedFriend.Columns.Visibility; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColumnVisibility, v => GameSummariesFriendsOverviewSelectedFriend.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> FriendsOverviewSelectedFriendGameSummariesColumnWidths { get => GameSummariesFriendsOverviewSelectedFriend.Columns.Widths; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColumnWidths, v => GameSummariesFriendsOverviewSelectedFriend.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> FriendsOverviewSelectedFriendGameSummariesColumnOrder { get => GameSummariesFriendsOverviewSelectedFriend.Columns.Order; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColumnOrder, v => GameSummariesFriendsOverviewSelectedFriend.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewSelectedFriendGameSummariesColumnAlignments { get => GameSummariesFriendsOverviewSelectedFriend.Columns.CellAlignments; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColumnAlignments, v => GameSummariesFriendsOverviewSelectedFriend.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> FriendsOverviewSelectedFriendGameSummariesColumnVerticalAlignments { get => GameSummariesFriendsOverviewSelectedFriend.Columns.CellVerticalAlignments; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColumnVerticalAlignments, v => GameSummariesFriendsOverviewSelectedFriend.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewSelectedFriendGameSummariesColumnHeaderAlignments { get => GameSummariesFriendsOverviewSelectedFriend.Columns.HeaderAlignments; set => SetGridValue(FriendsOverviewSelectedFriendGameSummariesColumnHeaderAlignments, v => GameSummariesFriendsOverviewSelectedFriend.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> OverviewSelectedGameAchievementColumnVisibility { get => AchievementOverviewSelectedGame.Columns.Visibility; set => SetGridValue(OverviewSelectedGameAchievementColumnVisibility, v => AchievementOverviewSelectedGame.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> OverviewSelectedGameAchievementColumnWidths { get => AchievementOverviewSelectedGame.Columns.Widths; set => SetGridValue(OverviewSelectedGameAchievementColumnWidths, v => AchievementOverviewSelectedGame.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> OverviewSelectedGameAchievementColumnOrder { get => AchievementOverviewSelectedGame.Columns.Order; set => SetGridValue(OverviewSelectedGameAchievementColumnOrder, v => AchievementOverviewSelectedGame.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewSelectedGameAchievementColumnAlignments { get => AchievementOverviewSelectedGame.Columns.CellAlignments; set => SetGridValue(OverviewSelectedGameAchievementColumnAlignments, v => AchievementOverviewSelectedGame.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> OverviewSelectedGameAchievementColumnVerticalAlignments { get => AchievementOverviewSelectedGame.Columns.CellVerticalAlignments; set => SetGridValue(OverviewSelectedGameAchievementColumnVerticalAlignments, v => AchievementOverviewSelectedGame.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewSelectedGameAchievementColumnHeaderAlignments { get => AchievementOverviewSelectedGame.Columns.HeaderAlignments; set => SetGridValue(OverviewSelectedGameAchievementColumnHeaderAlignments, v => AchievementOverviewSelectedGame.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> SingleGameColumnVisibility { get => AchievementSingleGame.Columns.Visibility; set => SetGridValue(SingleGameColumnVisibility, v => AchievementSingleGame.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> SingleGameColumnWidths { get => AchievementSingleGame.Columns.Widths; set => SetGridValue(SingleGameColumnWidths, v => AchievementSingleGame.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> SingleGameColumnOrder { get => AchievementSingleGame.Columns.Order; set => SetGridValue(SingleGameColumnOrder, v => AchievementSingleGame.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> SingleGameColumnAlignments { get => AchievementSingleGame.Columns.CellAlignments; set => SetGridValue(SingleGameColumnAlignments, v => AchievementSingleGame.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> SingleGameColumnVerticalAlignments { get => AchievementSingleGame.Columns.CellVerticalAlignments; set => SetGridValue(SingleGameColumnVerticalAlignments, v => AchievementSingleGame.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> SingleGameColumnHeaderAlignments { get => AchievementSingleGame.Columns.HeaderAlignments; set => SetGridValue(SingleGameColumnHeaderAlignments, v => AchievementSingleGame.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, double> DesktopThemeColumnWidths { get => AchievementDesktopTheme.Columns.Widths; set => SetGridValue(DesktopThemeColumnWidths, v => AchievementDesktopTheme.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> DesktopThemeColumnOrder { get => AchievementDesktopTheme.Columns.Order; set => SetGridValue(DesktopThemeColumnOrder, v => AchievementDesktopTheme.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> DesktopThemeColumnAlignments { get => AchievementDesktopTheme.Columns.CellAlignments; set => SetGridValue(DesktopThemeColumnAlignments, v => AchievementDesktopTheme.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> DesktopThemeColumnVerticalAlignments { get => AchievementDesktopTheme.Columns.CellVerticalAlignments; set => SetGridValue(DesktopThemeColumnVerticalAlignments, v => AchievementDesktopTheme.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> DesktopThemeColumnHeaderAlignments { get => AchievementDesktopTheme.Columns.HeaderAlignments; set => SetGridValue(DesktopThemeColumnHeaderAlignments, v => AchievementDesktopTheme.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> OverviewGameSummariesColumnVisibility { get => GameSummariesOverview.Columns.Visibility; set => SetGridValue(OverviewGameSummariesColumnVisibility, v => GameSummariesOverview.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> OverviewGameSummariesColumnWidths { get => GameSummariesOverview.Columns.Widths; set => SetGridValue(OverviewGameSummariesColumnWidths, v => GameSummariesOverview.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> OverviewGameSummariesColumnOrder { get => GameSummariesOverview.Columns.Order; set => SetGridValue(OverviewGameSummariesColumnOrder, v => GameSummariesOverview.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewGameSummariesColumnAlignments { get => GameSummariesOverview.Columns.CellAlignments; set => SetGridValue(OverviewGameSummariesColumnAlignments, v => GameSummariesOverview.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> OverviewGameSummariesColumnVerticalAlignments { get => GameSummariesOverview.Columns.CellVerticalAlignments; set => SetGridValue(OverviewGameSummariesColumnVerticalAlignments, v => GameSummariesOverview.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewGameSummariesColumnHeaderAlignments { get => GameSummariesOverview.Columns.HeaderAlignments; set => SetGridValue(OverviewGameSummariesColumnHeaderAlignments, v => GameSummariesOverview.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> ViewAchievementsGameSummariesColumnVisibility { get => GameSummariesViewAchievements.Columns.Visibility; set => SetGridValue(ViewAchievementsGameSummariesColumnVisibility, v => GameSummariesViewAchievements.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> ViewAchievementsGameSummariesColumnWidths { get => GameSummariesViewAchievements.Columns.Widths; set => SetGridValue(ViewAchievementsGameSummariesColumnWidths, v => GameSummariesViewAchievements.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> ViewAchievementsGameSummariesColumnOrder { get => GameSummariesViewAchievements.Columns.Order; set => SetGridValue(ViewAchievementsGameSummariesColumnOrder, v => GameSummariesViewAchievements.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> ViewAchievementsGameSummariesColumnAlignments { get => GameSummariesViewAchievements.Columns.CellAlignments; set => SetGridValue(ViewAchievementsGameSummariesColumnAlignments, v => GameSummariesViewAchievements.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> ViewAchievementsGameSummariesColumnVerticalAlignments { get => GameSummariesViewAchievements.Columns.CellVerticalAlignments; set => SetGridValue(ViewAchievementsGameSummariesColumnVerticalAlignments, v => GameSummariesViewAchievements.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> ViewAchievementsGameSummariesColumnHeaderAlignments { get => GameSummariesViewAchievements.Columns.HeaderAlignments; set => SetGridValue(ViewAchievementsGameSummariesColumnHeaderAlignments, v => GameSummariesViewAchievements.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> ViewAchievementsCategorySummariesColumnVisibility { get => CategorySummariesViewAchievements.Columns.Visibility; set => SetGridValue(ViewAchievementsCategorySummariesColumnVisibility, v => CategorySummariesViewAchievements.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> ViewAchievementsCategorySummariesColumnWidths { get => CategorySummariesViewAchievements.Columns.Widths; set => SetGridValue(ViewAchievementsCategorySummariesColumnWidths, v => CategorySummariesViewAchievements.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> ViewAchievementsCategorySummariesColumnOrder { get => CategorySummariesViewAchievements.Columns.Order; set => SetGridValue(ViewAchievementsCategorySummariesColumnOrder, v => CategorySummariesViewAchievements.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> ViewAchievementsCategorySummariesColumnAlignments { get => CategorySummariesViewAchievements.Columns.CellAlignments; set => SetGridValue(ViewAchievementsCategorySummariesColumnAlignments, v => CategorySummariesViewAchievements.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> ViewAchievementsCategorySummariesColumnVerticalAlignments { get => CategorySummariesViewAchievements.Columns.CellVerticalAlignments; set => SetGridValue(ViewAchievementsCategorySummariesColumnVerticalAlignments, v => CategorySummariesViewAchievements.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> ViewAchievementsCategorySummariesColumnHeaderAlignments { get => CategorySummariesViewAchievements.Columns.HeaderAlignments; set => SetGridValue(ViewAchievementsCategorySummariesColumnHeaderAlignments, v => CategorySummariesViewAchievements.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> OverviewSelectedGameCategorySummariesColumnVisibility { get => CategorySummariesOverviewSelectedGame.Columns.Visibility; set => SetGridValue(OverviewSelectedGameCategorySummariesColumnVisibility, v => CategorySummariesOverviewSelectedGame.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> OverviewSelectedGameCategorySummariesColumnWidths { get => CategorySummariesOverviewSelectedGame.Columns.Widths; set => SetGridValue(OverviewSelectedGameCategorySummariesColumnWidths, v => CategorySummariesOverviewSelectedGame.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> OverviewSelectedGameCategorySummariesColumnOrder { get => CategorySummariesOverviewSelectedGame.Columns.Order; set => SetGridValue(OverviewSelectedGameCategorySummariesColumnOrder, v => CategorySummariesOverviewSelectedGame.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewSelectedGameCategorySummariesColumnAlignments { get => CategorySummariesOverviewSelectedGame.Columns.CellAlignments; set => SetGridValue(OverviewSelectedGameCategorySummariesColumnAlignments, v => CategorySummariesOverviewSelectedGame.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> OverviewSelectedGameCategorySummariesColumnVerticalAlignments { get => CategorySummariesOverviewSelectedGame.Columns.CellVerticalAlignments; set => SetGridValue(OverviewSelectedGameCategorySummariesColumnVerticalAlignments, v => CategorySummariesOverviewSelectedGame.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> OverviewSelectedGameCategorySummariesColumnHeaderAlignments { get => CategorySummariesOverviewSelectedGame.Columns.HeaderAlignments; set => SetGridValue(OverviewSelectedGameCategorySummariesColumnHeaderAlignments, v => CategorySummariesOverviewSelectedGame.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> FriendsOverviewCategorySummariesColumnVisibility { get => CategorySummariesFriendsOverview.Columns.Visibility; set => SetGridValue(FriendsOverviewCategorySummariesColumnVisibility, v => CategorySummariesFriendsOverview.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> FriendsOverviewCategorySummariesColumnWidths { get => CategorySummariesFriendsOverview.Columns.Widths; set => SetGridValue(FriendsOverviewCategorySummariesColumnWidths, v => CategorySummariesFriendsOverview.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> FriendsOverviewCategorySummariesColumnOrder { get => CategorySummariesFriendsOverview.Columns.Order; set => SetGridValue(FriendsOverviewCategorySummariesColumnOrder, v => CategorySummariesFriendsOverview.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewCategorySummariesColumnAlignments { get => CategorySummariesFriendsOverview.Columns.CellAlignments; set => SetGridValue(FriendsOverviewCategorySummariesColumnAlignments, v => CategorySummariesFriendsOverview.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> FriendsOverviewCategorySummariesColumnVerticalAlignments { get => CategorySummariesFriendsOverview.Columns.CellVerticalAlignments; set => SetGridValue(FriendsOverviewCategorySummariesColumnVerticalAlignments, v => CategorySummariesFriendsOverview.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> FriendsOverviewCategorySummariesColumnHeaderAlignments { get => CategorySummariesFriendsOverview.Columns.HeaderAlignments; set => SetGridValue(FriendsOverviewCategorySummariesColumnHeaderAlignments, v => CategorySummariesFriendsOverview.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> DesktopThemeCategorySummariesColumnVisibility { get => CategorySummariesDesktopTheme.Columns.Visibility; set => SetGridValue(DesktopThemeCategorySummariesColumnVisibility, v => CategorySummariesDesktopTheme.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> DesktopThemeCategorySummariesColumnWidths { get => CategorySummariesDesktopTheme.Columns.Widths; set => SetGridValue(DesktopThemeCategorySummariesColumnWidths, v => CategorySummariesDesktopTheme.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> DesktopThemeCategorySummariesColumnOrder { get => CategorySummariesDesktopTheme.Columns.Order; set => SetGridValue(DesktopThemeCategorySummariesColumnOrder, v => CategorySummariesDesktopTheme.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> DesktopThemeCategorySummariesColumnAlignments { get => CategorySummariesDesktopTheme.Columns.CellAlignments; set => SetGridValue(DesktopThemeCategorySummariesColumnAlignments, v => CategorySummariesDesktopTheme.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> DesktopThemeCategorySummariesColumnVerticalAlignments { get => CategorySummariesDesktopTheme.Columns.CellVerticalAlignments; set => SetGridValue(DesktopThemeCategorySummariesColumnVerticalAlignments, v => CategorySummariesDesktopTheme.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> DesktopThemeCategorySummariesColumnHeaderAlignments { get => CategorySummariesDesktopTheme.Columns.HeaderAlignments; set => SetGridValue(DesktopThemeCategorySummariesColumnHeaderAlignments, v => CategorySummariesDesktopTheme.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public bool ShowViewAchievementsCategorySummariesGridColumnHeaders { get => CategorySummariesViewAchievements.ShowColumnHeaders; set => SetGridValue(ShowViewAchievementsCategorySummariesGridColumnHeaders, v => CategorySummariesViewAchievements.ShowColumnHeaders = v, value); }
        [JsonIgnore] public double? ViewAchievementsCategorySummariesGridRowHeight { get => CategorySummariesViewAchievements.RowHeight; set => SetGridValue(ViewAchievementsCategorySummariesGridRowHeight, v => CategorySummariesViewAchievements.RowHeight = v, value); }
        [JsonIgnore] public bool ViewAchievementsCategorySummariesUseCoverImages { get => CategorySummariesViewAchievements.UseCoverImages; set => SetGridValue(ViewAchievementsCategorySummariesUseCoverImages, v => CategorySummariesViewAchievements.UseCoverImages = v, value); }
        [JsonIgnore] public bool ViewAchievementsCategorySummariesShowCompletionGlow { get => CategorySummariesViewAchievements.ShowCompletionGlow; set => SetGridValue(ViewAchievementsCategorySummariesShowCompletionGlow, v => CategorySummariesViewAchievements.ShowCompletionGlow = v, value); }
        [JsonIgnore] public bool ShowOverviewSelectedGameCategorySummariesGridColumnHeaders { get => CategorySummariesOverviewSelectedGame.ShowColumnHeaders; set => SetGridValue(ShowOverviewSelectedGameCategorySummariesGridColumnHeaders, v => CategorySummariesOverviewSelectedGame.ShowColumnHeaders = v, value); }
        [JsonIgnore] public double? OverviewSelectedGameCategorySummariesGridRowHeight { get => CategorySummariesOverviewSelectedGame.RowHeight; set => SetGridValue(OverviewSelectedGameCategorySummariesGridRowHeight, v => CategorySummariesOverviewSelectedGame.RowHeight = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameCategorySummariesUseCoverImages { get => CategorySummariesOverviewSelectedGame.UseCoverImages; set => SetGridValue(OverviewSelectedGameCategorySummariesUseCoverImages, v => CategorySummariesOverviewSelectedGame.UseCoverImages = v, value); }
        [JsonIgnore] public bool OverviewSelectedGameCategorySummariesShowCompletionGlow { get => CategorySummariesOverviewSelectedGame.ShowCompletionGlow; set => SetGridValue(OverviewSelectedGameCategorySummariesShowCompletionGlow, v => CategorySummariesOverviewSelectedGame.ShowCompletionGlow = v, value); }
        [JsonIgnore] public bool ShowFriendsOverviewCategorySummariesGridColumnHeaders { get => CategorySummariesFriendsOverview.ShowColumnHeaders; set => SetGridValue(ShowFriendsOverviewCategorySummariesGridColumnHeaders, v => CategorySummariesFriendsOverview.ShowColumnHeaders = v, value); }
        [JsonIgnore] public double? FriendsOverviewCategorySummariesGridRowHeight { get => CategorySummariesFriendsOverview.RowHeight; set => SetGridValue(FriendsOverviewCategorySummariesGridRowHeight, v => CategorySummariesFriendsOverview.RowHeight = v, value); }
        [JsonIgnore] public bool FriendsOverviewCategorySummariesUseCoverImages { get => CategorySummariesFriendsOverview.UseCoverImages; set => SetGridValue(FriendsOverviewCategorySummariesUseCoverImages, v => CategorySummariesFriendsOverview.UseCoverImages = v, value); }
        [JsonIgnore] public bool FriendsOverviewCategorySummariesShowCompletionGlow { get => CategorySummariesFriendsOverview.ShowCompletionGlow; set => SetGridValue(FriendsOverviewCategorySummariesShowCompletionGlow, v => CategorySummariesFriendsOverview.ShowCompletionGlow = v, value); }
        [JsonIgnore] public bool ShowDesktopThemeCategorySummariesGridColumnHeaders { get => CategorySummariesDesktopTheme.ShowColumnHeaders; set => SetGridValue(ShowDesktopThemeCategorySummariesGridColumnHeaders, v => CategorySummariesDesktopTheme.ShowColumnHeaders = v, value); }
        [JsonIgnore] public double? DesktopThemeCategorySummariesGridRowHeight { get => CategorySummariesDesktopTheme.RowHeight; set => SetGridValue(DesktopThemeCategorySummariesGridRowHeight, v => CategorySummariesDesktopTheme.RowHeight = v, value); }
        [JsonIgnore] public bool DesktopThemeCategorySummariesUseCoverImages { get => CategorySummariesDesktopTheme.UseCoverImages; set => SetGridValue(DesktopThemeCategorySummariesUseCoverImages, v => CategorySummariesDesktopTheme.UseCoverImages = v, value); }
        [JsonIgnore] public bool DesktopThemeCategorySummariesShowCompletionGlow { get => CategorySummariesDesktopTheme.ShowCompletionGlow; set => SetGridValue(DesktopThemeCategorySummariesShowCompletionGlow, v => CategorySummariesDesktopTheme.ShowCompletionGlow = v, value); }
        [JsonIgnore] public Dictionary<string, bool> StartPageAchievementColumnVisibility { get => AchievementStartPageRecent.Columns.Visibility; set => SetGridValue(StartPageAchievementColumnVisibility, v => AchievementStartPageRecent.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> StartPageAchievementColumnWidths { get => AchievementStartPageRecent.Columns.Widths; set => SetGridValue(StartPageAchievementColumnWidths, v => AchievementStartPageRecent.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> StartPageAchievementColumnOrder { get => AchievementStartPageRecent.Columns.Order; set => SetGridValue(StartPageAchievementColumnOrder, v => AchievementStartPageRecent.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> StartPageAchievementColumnAlignments { get => AchievementStartPageRecent.Columns.CellAlignments; set => SetGridValue(StartPageAchievementColumnAlignments, v => AchievementStartPageRecent.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> StartPageAchievementColumnVerticalAlignments { get => AchievementStartPageRecent.Columns.CellVerticalAlignments; set => SetGridValue(StartPageAchievementColumnVerticalAlignments, v => AchievementStartPageRecent.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> StartPageAchievementColumnHeaderAlignments { get => AchievementStartPageRecent.Columns.HeaderAlignments; set => SetGridValue(StartPageAchievementColumnHeaderAlignments, v => AchievementStartPageRecent.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> StartPageFriendAchievementColumnVisibility { get => AchievementStartPageFriendRecent.Columns.Visibility; set => SetGridValue(StartPageFriendAchievementColumnVisibility, v => AchievementStartPageFriendRecent.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> StartPageFriendAchievementColumnWidths { get => AchievementStartPageFriendRecent.Columns.Widths; set => SetGridValue(StartPageFriendAchievementColumnWidths, v => AchievementStartPageFriendRecent.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> StartPageFriendAchievementColumnOrder { get => AchievementStartPageFriendRecent.Columns.Order; set => SetGridValue(StartPageFriendAchievementColumnOrder, v => AchievementStartPageFriendRecent.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> StartPageFriendAchievementColumnAlignments { get => AchievementStartPageFriendRecent.Columns.CellAlignments; set => SetGridValue(StartPageFriendAchievementColumnAlignments, v => AchievementStartPageFriendRecent.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> StartPageFriendAchievementColumnVerticalAlignments { get => AchievementStartPageFriendRecent.Columns.CellVerticalAlignments; set => SetGridValue(StartPageFriendAchievementColumnVerticalAlignments, v => AchievementStartPageFriendRecent.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> StartPageFriendAchievementColumnHeaderAlignments { get => AchievementStartPageFriendRecent.Columns.HeaderAlignments; set => SetGridValue(StartPageFriendAchievementColumnHeaderAlignments, v => AchievementStartPageFriendRecent.Columns.HeaderAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, bool> StartPageGameSummariesColumnVisibility { get => GameSummariesStartPage.Columns.Visibility; set => SetGridValue(StartPageGameSummariesColumnVisibility, v => GameSummariesStartPage.Columns.Visibility = v, value); }
        [JsonIgnore] public Dictionary<string, double> StartPageGameSummariesColumnWidths { get => GameSummariesStartPage.Columns.Widths; set => SetGridValue(StartPageGameSummariesColumnWidths, v => GameSummariesStartPage.Columns.Widths = v, value); }
        [JsonIgnore] public Dictionary<string, int> StartPageGameSummariesColumnOrder { get => GameSummariesStartPage.Columns.Order; set => SetGridValue(StartPageGameSummariesColumnOrder, v => GameSummariesStartPage.Columns.Order = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> StartPageGameSummariesColumnAlignments { get => GameSummariesStartPage.Columns.CellAlignments; set => SetGridValue(StartPageGameSummariesColumnAlignments, v => GameSummariesStartPage.Columns.CellAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridVerticalAlignment> StartPageGameSummariesColumnVerticalAlignments { get => GameSummariesStartPage.Columns.CellVerticalAlignments; set => SetGridValue(StartPageGameSummariesColumnVerticalAlignments, v => GameSummariesStartPage.Columns.CellVerticalAlignments = v, value); }
        [JsonIgnore] public Dictionary<string, GridAlignment> StartPageGameSummariesColumnHeaderAlignments { get => GameSummariesStartPage.Columns.HeaderAlignments; set => SetGridValue(StartPageGameSummariesColumnHeaderAlignments, v => GameSummariesStartPage.Columns.HeaderAlignments = v, value); }
    }
}
